apiVersion: v1
kind: Service
metadata:
  name: model-serving-service
  labels:
    app: model-serving
spec:
  selector:
    app: model-serving
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP