name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r data-ingestion/requirements.txt
        pip install -r model-training/requirements.txt

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Set up Scala
      uses: olafurpg/setup-scala@v11

    - name: Install Maven dependencies
      run: |
        mvn -f data-ingestion/pom.xml install
        mvn -f model-training/pom.xml install

    - name: Run unit tests for Python
      run: |
        python -m unittest discover -s data-ingestion/tests
        python -m unittest discover -s model-training/tests

    - name: Run Scala tests
      run: |
        sbt test

  docker-build:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image for data ingestion
      run: |
        docker build -t data-ingestion ./data-ingestion

    - name: Build Docker image for model training
      run: |
        docker build -t model-training ./model-training

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f model-serving/Kubernetes/deployment.yaml
        kubectl apply -f model-serving/Kubernetes/service.yaml

    - name: Verify deployment
      run: |
        kubectl rollout status deployment/model-serving